### ISSUE TITLE
Filtering intents by state?

### ISSUE THREAD

**Issue by saik0** [oldergod/android-architecture#15]
I'm implementing an MVI that draws alot of inspiration form here, great work.

In my application some actions can only be performed from certain states. (Example: The user should only be able to submit a form that has passed validation, and cant submit when a request is in flight)

I'm thinking the cleanest approach is to filter the intent stream, and log/throw/ignore when the intent cant be transformed into an action for the current state.

However, the state resides in the state reducer, it is not accessible to the intent transformer. I'm not sure how to implement the desired behavior, and would greatly appreciate your feedback.

**Comment by oldergod** [comment]
How about adding that info inside the state?

Like you could have

```java
class State {
  // you validate your form inside the ViewModel or somewhere. (Out of the UI)
  boolean isFormValid;
  // Depends on your code but basically,
  // you would want to be able to know if a request is in flight.
  RequestStatus requestStatus;
}
```

then inside your UI, you would just reflect based on the state.

```java
class MyActivity {
  void render(State state) {
    if (state.isFormValid || requestStatus != IN_FLIGHT) {
      submitButton.enabled = true
    } else {
      submitButton.enabled = false
    }
  }
}
```

**Comment by saik0** [comment]
Yes. This was my thought as well, however:
  * It places the burden of ensuring the intent to perform a  state transition is legal on the view. The view should be passive, no?
 * The view state might not be delivered

**Comment by saik0** [comment]
Whoops hit the close and comment button. Haha.

 * The view state might not be delivered to the view before the user emits another submit intent.
 * The spec I was handed says the button should not be disabled  ¯\_(ツ)_/¯

**Comment by oldergod** [comment]
- It places the burden of ensuring the intent to perform a state transition is legal on the view. The view should be passive, no?

The View is not ensuring anything. It only renders the screen based on a state, and listens to the user. The fact that you can or cannot hit a button is a state that the UI only reflects onto the screen.

- The view state might not be delivered to the view before the user emits another submit intent.

If you only change threads inside the processors, the data flow itself is on the main thread so that's unlikely. If you want to be sure only one click can happen per frame, you can use something like ButterKnife's [DebouncingOnClickListener.java](https://github.com/JakeWharton/butterknife/blob/a677bf78c17e628606acaad05ffdd7e2b71c8843/butterknife/src/main/java/butterknife/internal/DebouncingOnClickListener.java).

- The spec I was handed says the button should not be disabled ¯_(ツ)_/¯

You could have a flag then somewhere and do something like `RxView(submitButton).clicks().filter(ignored -> canSubmit).map( ignored -> SubmitIntent())`
