### ISSUE TITLE
.scan(initialIntentFilter)

### ISSUE THREAD

**Issue by feresr** [oldergod/android-architecture#5]
I really like this architecture! and I'm curious about 2 things, I'm not an expert on RxJava so take these with a grain of salt:

**All related to `TaskViewModel.class`:**

1 -  What's the reason for using two `PublishSubjects` instead of one `PublishSubject` and one `BehaviourSubject` that would automatically trigger the last `TaskViewState` to its subscribers?
Alternatively I believe the same behaviour can be achieved using one `PublishSubject` + `replay(1).autoConnect()` or Jake Warthon's library https://github.com/JakeWharton/RxReplayingShare

2 - On line `53` you do `compose().subscribe(this.mStatesSubject);`. shouldn't you store that  `disposable` and call `.dispose` on `ViewModel::onCleared()`? I'm asking because I truly don't know if you should

Similarly, on line `58`: `intents.subscribe(mIntentsSubject);`:  
I'm guessing the `intents` observable has some kind of reference to the view (RxBindings), as the view gets destroyed will that translate to a memory leak? or it unsubscribes automatically for us?
If it's the latter, `processIntents` could return a `Disposable` to the view perhaps?

**Comment by oldergod** [comment]
First of all, I'm in no way an expert either. I just made up something that matched my thinking.

1 - I've already been told I could remove the `initialIntentFilter` if I used a `BehaviourSubject`. I actually thought about it and tried to find a solution but I just didn't find any I'd be satisfied with.  
If I were to use a `BehaviourSubject` in the VM, I imagine I'd remove the `InitialIntent` from the view but then who would initiate the first action (like the loading of the data)? Without it, the first _idle/default_ `ViewState` emitted from the VM on subscription would contain no data. Should the VM getting the data the first time? That's where my thinking stopped and I gave up because I don't think the VM should be doing this.  
If you have an implementation in mind that makes sense, I'd be happy to see it!

2 - Both lines, because it is actually a subject (`implements Observer`) which subscribes,  are actually calling `Observable#subscribe(Observer<? super T> observer)` which returns `void` so this is technically not possible. Although, to tell you the whole truth, I'm not sure why it's not needed here.

**Comment by feresr** [comment]
1 - Point taken. You bring up a fair point, I hadn't thought about that **initial Intent**. I'm thinking this could fixed by introducing a new property in `TasksViewState` like `boolean initial = true`, and making this the **default** `ViewState`. 
Then: 
```
    public void render(TasksViewState state) {
        if (state.initial) {
            mRefreshIntentPublisher.onNext(someIntent); //refresh or Intial intent
            return
        }
        ...
    }
```
This will trigger an Intent to fetch data which will immediately generate a new ViewState with `initial = false; inProgress = true;`.

2- You are right!, `Observable#subscribe(Observer o)` returns `Void`. The reason I'm able to retrieve a `subscription/disposable` from it it's because I'm using `Relays` (library). It's strange since I thought a `relay` was essentially a `subject`, but it's acting as a `consumer` in this case and `Observable#subscribe(Consumer o)` returns a `Disposable`. 
Take a look at this StackOverflow post for how to get a `Disposable` when using `Subjects` https://stackoverflow.com/questions/41018023/how-to-get-a-disposable-for-subjects-as-subscriber-in-rxjava2
Again, I'm unsure if it is even necessary to unsubscribe in the first place

**Comment by oldergod** [comment]
1 - That could be a solution indeed. I don't think intent should be results of rendering a state though.

2 - I don't think there is a problem so getting the disposable is not necessary I guess?

**Comment by feresr** [comment]
1 - Yup I agree, this approach is not necessarily better than the current one, just different.
2 -You are probably right, and if this indeed proves to be an issue later on, it can be easily fixed
